{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cert-monitor.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cert-monitor.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  ADMIN_USERNAME: {{ .Values.secret.adminUsername | quote }}
  ADMIN_PASSWORD: {{ .Values.secret.adminPassword | quote }}
  DB_PASSWORD: {{ .Values.secret.dbPassword | quote }}
  SMTP_USER: {{ .Values.secret.smtpUser | quote }}
  SMTP_PASSWORD: {{ .Values.secret.smtpPassword | quote }}
  EMAIL_TO: {{ .Values.secret.emailTo | quote }}
  EMAIL_FROM: {{ .Values.secret.emailFrom | quote }}
{{- end }}
