package com.sitemonitor.service;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Rename VERİ göçü (SchedulerService.applySchemaPatches içindeki iki UPDATE) semantiği:
 * app_settings.setting_key 'cert.monitor.%' → 'site.monitor.%' ve
 * 'logging.level.com.certmonitor%' → 'logging.level.com.sitemonitor%'.
 *
 * SQL metinleri SchedulerService'tekiyle AYNI tutulmalıdır (oradan kopya) — patch()
 * hataları DEBUG'a yutulduğu için sözdizimi/semantik hatası prod'da SESSİZCE tüm admin
 * override'larını varsayılana döndürürdü; bu test o riski kırmızıya çevirir.
 */
class AppSettingsRenameMigrationTest {

    // SchedulerService.applySchemaPatches ile birebir aynı (senkron tut!)
    private static final String MIGRATE_PREFIX =
            "UPDATE app_settings SET setting_key = 'site.monitor.' || substring(setting_key, 14) "
                    + "WHERE setting_key LIKE 'cert.monitor.%' "
                    + "AND NOT EXISTS (SELECT 1 FROM app_settings s2 "
                    + "WHERE s2.setting_key = 'site.monitor.' || substring(app_settings.setting_key, 14))";
    private static final String MIGRATE_LOGGER =
            "UPDATE app_settings SET setting_key = 'logging.level.com.sitemonitor' || substring(setting_key, 30) "
                    + "WHERE setting_key LIKE 'logging.level.com.certmonitor%' "
                    + "AND NOT EXISTS (SELECT 1 FROM app_settings s2 "
                    + "WHERE s2.setting_key = 'logging.level.com.sitemonitor' || substring(app_settings.setting_key, 30))";

    private JdbcTemplate jdbc;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource ds = new DriverManagerDataSource(
                "jdbc:h2:mem:renametest;DB_CLOSE_DELAY=-1;MODE=PostgreSQL", "sa", "");
        jdbc = new JdbcTemplate(ds);
        jdbc.update("DROP TABLE IF EXISTS app_settings");
        jdbc.update("CREATE TABLE app_settings(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                + "setting_key VARCHAR(150) NOT NULL UNIQUE, setting_value TEXT)");
    }

    private void insert(String key, String value) {
        jdbc.update("INSERT INTO app_settings(setting_key, setting_value) VALUES (?, ?)", key, value);
    }

    private List<String> keys() {
        return jdbc.queryForList("SELECT setting_key FROM app_settings ORDER BY setting_key", String.class);
    }

    @Test
    void eskiOneklerYeniAdaTasinir_degerlerKorunur() {
        insert("cert.monitor.storm.enabled", "true");
        insert("cert.monitor.page.default-timeout-ms", "9000");
        insert("logging.level.com.certmonitor", "INFO");
        insert("logging.level.com.certmonitor.mail", "TRACE");
        insert("smtp.unrelated", "x");   // dokunulmamalı

        jdbc.update(MIGRATE_PREFIX);
        jdbc.update(MIGRATE_LOGGER);

        assertThat(keys()).containsExactly(
                "logging.level.com.sitemonitor",
                "logging.level.com.sitemonitor.mail",
                "site.monitor.page.default-timeout-ms",
                "site.monitor.storm.enabled",
                "smtp.unrelated");
        assertThat(jdbc.queryForObject(
                "SELECT setting_value FROM app_settings WHERE setting_key='site.monitor.page.default-timeout-ms'",
                String.class)).isEqualTo("9000");
        assertThat(jdbc.queryForObject(
                "SELECT setting_value FROM app_settings WHERE setting_key='logging.level.com.sitemonitor.mail'",
                String.class)).isEqualTo("TRACE");
    }

    @Test
    void cakismaGuardi_yeniAdVarsa_eskiSatirDokunulmaz() {
        insert("cert.monitor.storm.enabled", "eski");
        insert("site.monitor.storm.enabled", "yeni");   // yeni ad zaten var → eski satır kalmalı

        jdbc.update(MIGRATE_PREFIX);

        assertThat(keys()).containsExactly("cert.monitor.storm.enabled", "site.monitor.storm.enabled");
        assertThat(jdbc.queryForObject(
                "SELECT setting_value FROM app_settings WHERE setting_key='site.monitor.storm.enabled'",
                String.class)).isEqualTo("yeni");
    }

    @Test
    void idempotent_ikinciKosuNoOp() {
        insert("cert.monitor.storm.enabled", "true");
        jdbc.update(MIGRATE_PREFIX);
        int second = jdbc.update(MIGRATE_PREFIX);
        assertThat(second).isZero();
        assertThat(keys()).containsExactly("site.monitor.storm.enabled");
    }
}
