package com.sitemonitor.service;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Kart mini trendi (2026-09-12): NATİF SQL gerçek motorda (H2, Postgres kipi) koşar — kova/pencere
 * sözdizimi ve sütun adları (Hibernate snake_case) burada doğrulanır. Tarihler KAYAN (now'dan).
 */
class MonitorSparklineServiceTest {

    private static final DateTimeFormatter ISO =
            DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss").withZone(ZoneOffset.UTC);

    JdbcTemplate jdbc;
    MonitorSparklineService svc;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource ds = new DriverManagerDataSource(
                "jdbc:h2:mem:sparktest;DB_CLOSE_DELAY=-1;MODE=PostgreSQL", "sa", "");
        jdbc = new JdbcTemplate(ds);
        jdbc.update("DROP TABLE IF EXISTS http_checks");
        jdbc.update("DROP TABLE IF EXISTS http_monitors");
        jdbc.update("CREATE TABLE http_monitors(id BIGINT PRIMARY KEY, team_id BIGINT)");
        jdbc.update("CREATE TABLE http_checks(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, monitor_id BIGINT, "
                + "http_status INT, response_ms BIGINT, error VARCHAR(200), checked_at VARCHAR(19))");
        jdbc.update("INSERT INTO http_monitors VALUES (1, 5), (2, NULL), (3, 7)");
        svc = new MonitorSparklineService(jdbc);
    }

    private void check(long monitorId, int minutesAgo, Long ms, String error) {
        checkAt(monitorId, Instant.now().minus(minutesAgo, ChronoUnit.MINUTES), ms, error);
    }

    private void checkAt(long monitorId, Instant at, Long ms, String error) {
        jdbc.update("INSERT INTO http_checks(monitor_id, http_status, response_ms, error, checked_at) VALUES (?,?,?,?,?)",
                monitorId, error == null ? 200 : null, ms, error, ISO.format(at));
    }

    @Test
    @DisplayName("monitorTeams: id → takım (null takım korunur)")
    void monitorTeams() {
        Map<Long, Long> t = svc.monitorTeams("http");
        assertThat(t).containsEntry(1L, 5L).containsEntry(3L, 7L).containsKey(2L);
        assertThat(t.get(2L)).isNull();
    }

    @Test
    @DisplayName("sparklines: saatlik kovalar (adet/hata/ort. süre), son 5 kontrol kronolojik, up_pct; pencere dışı satır sayılmaz; görünmeyen id dönmez")
    void sparklines_bucketsLastAndUpPct() {
        // monitör 1: 7 kontrol son 2 saatte, biri hatalı; 1 kontrol 30 saat önce (pencere dışı)
        check(1, 5,   200L, null);
        check(1, 15,  300L, null);
        check(1, 25,  null, "timeout");
        check(1, 35,  250L, null);
        check(1, 45,  210L, null);
        check(1, 70,  400L, null);
        check(1, 100, 500L, null);
        check(1, 30 * 60, 999L, null);
        // monitör 3: hiç kontrol yok — yine de kayıt döner (n=0, up_pct null)
        Map<Long, Map<String, Object>> out = svc.sparklines("http", 24, Set.of(1L, 3L));

        assertThat(out).containsKeys(1L, 3L).doesNotContainKey(2L);
        Map<String, Object> m1 = out.get(1L);
        assertThat(m1).containsEntry("n", 7).containsEntry("fail", 1);
        assertThat((Double) m1.get("up_pct")).isEqualTo(85.7);
        @SuppressWarnings("unchecked") List<Map<String, Object>> buckets = (List<Map<String, Object>>) m1.get("buckets");
        assertThat(buckets).isNotEmpty();
        assertThat(buckets.stream().mapToInt(b -> (Integer) b.get("n")).sum()).isEqualTo(7);
        assertThat(buckets.stream().mapToInt(b -> (Integer) b.get("fail")).sum()).isEqualTo(1);
        assertThat(buckets).allSatisfy(b -> assertThat(((String) b.get("t")).length()).isEqualTo(13));   // yyyy-MM-ddTHH
        @SuppressWarnings("unchecked") List<Map<String, Object>> last = (List<Map<String, Object>>) m1.get("last");
        assertThat(last).hasSize(5);
        assertThat(last.get(4)).containsEntry("ok", true).containsEntry("ms", 200L);      // en yeni sonda
        assertThat(last.get(2)).containsEntry("ok", false);                              // 25 dk önceki hata
        assertThat(last).extracting(c -> (String) c.get("at")).isSorted();

        Map<String, Object> m3 = out.get(3L);
        assertThat(m3).containsEntry("n", 0);
        assertThat(m3.get("up_pct")).isNull();
    }

    @Test
    @DisplayName("hours üst sınırı 168; desteklenmeyen tür false; boş id kümesi boş harita")
    void guards() {
        assertThat(MonitorSparklineService.supports("http")).isTrue();
        assertThat(MonitorSparklineService.supports("domain")).isFalse();
        assertThat(MonitorSparklineService.supports(null)).isFalse();
        assertThat(svc.sparklines("http", 9999, Set.of())).isEmpty();
        assertThat(MonitorSparklineService.KINDS).containsKeys("http", "ping", "port", "dns", "keyword", "page", "pagespeed", "scripted");
    }
    @Test
    @DisplayName("availability: 30 gün toplam/hata/yüzde (iki ondalık) + hatalı saat kovası; pencere dışı satır sayılmaz; gün tavanı 90")
    void availability() {
        check(1, 5,   200L, null);
        // İki hata AYNI saat kovasında olmalı: "65 dk / 66 dk önce" dakika sınırında (örn. CI 18:05'te) farklı
        // saatlere düşüyordu → bad_hours=2 (2026-09-13 CI kırmızısı). Kovayı açıkça sabitle: bir önceki tam saat +10/+20 dk.
        Instant hour = Instant.now().minus(65, ChronoUnit.MINUTES).truncatedTo(ChronoUnit.HOURS);
        checkAt(1, hour.plus(10, ChronoUnit.MINUTES), null, "timeout");
        checkAt(1, hour.plus(20, ChronoUnit.MINUTES), null, "timeout");   // aynı kova → bad_hours yine 1
        check(1, 3 * 24 * 60, 300L, null);
        check(1, 100 * 24 * 60, 300L, null);   // 100 gün önce — 90 gün tavanı dışında
        Map<Long, Map<String, Object>> out = svc.availability("http", 9999, Set.of(1L, 3L));
        Map<String, Object> m = out.get(1L);
        assertThat(m).containsEntry("n", 4).containsEntry("fail", 2).containsEntry("bad_hours", 1);
        assertThat((Double) m.get("up_pct")).isEqualTo(50.0);
        assertThat(out.get(3L)).containsEntry("n", 0).containsEntry("bad_hours", 0);
        assertThat(out.get(3L).get("up_pct")).isNull();
    }

    @SuppressWarnings("unchecked")
    private static Map<Integer, Map<String, Object>> windows(Map<String, Object> m) {
        Map<Integer, Map<String, Object>> byDays = new java.util.LinkedHashMap<>();
        for (Map<String, Object> w : (List<Map<String, Object>>) m.get("windows")) byDays.put((Integer) w.get("days"), w);
        return byDays;
    }

    @Test
    @DisplayName("availability windows (2026-09-24): 1/7/15/30 gün dönemleri aynı sorguda — adet/hata/yüzde/hatalı saat dönem içinden; kova başı dönemden önce olsa da yalnız dönem içi hata sayılır; kontrolsüz dönemde up_pct null")
    void availability_windows() {
        // NOW tam saatin 30. dakikası: kova sınırları CI saatinden bağımsız (sabit fixture tarihi değil — hepsi NOW'a göre).
        Instant now = Instant.now().truncatedTo(ChronoUnit.HOURS).plus(30, ChronoUnit.MINUTES);
        checkAt(1, now.minus(5, ChronoUnit.MINUTES), 200L, null);                  // 1 gün içinde, sağlıklı
        checkAt(1, now.minus(2, ChronoUnit.HOURS), null, "timeout");                // 1 gün içinde, hata (kova A)
        checkAt(1, now.minus(2, ChronoUnit.HOURS).plus(5, ChronoUnit.MINUTES), null, "timeout");   // aynı kova A
        checkAt(1, now.minus(3, ChronoUnit.DAYS), 300L, null);                      // 7 gün içinde
        checkAt(1, now.minus(10, ChronoUnit.DAYS), null, "503");                    // 15 gün içinde, hata (kova B)
        checkAt(1, now.minus(20, ChronoUnit.DAYS), 300L, null);                     // 30 gün içinde
        // Kova sınırı: 1 gün penceresi now−24sa = HH:30'da başlar. Aynı saat kovasında pencereden ÖNCE (HH:10) bir hata,
        // pencere içinde (HH:40) sağlıklı kontrol → 1 gün penceresinde o kova hatalı SAYILMAZ, 7 günde sayılır.
        Instant dayAgoHour = now.minus(24, ChronoUnit.HOURS).truncatedTo(ChronoUnit.HOURS);
        checkAt(1, dayAgoHour.plus(10, ChronoUnit.MINUTES), null, "timeout");       // kova C, 1 gün DIŞI
        checkAt(1, dayAgoHour.plus(40, ChronoUnit.MINUTES), 200L, null);            // kova C, 1 gün İÇİ

        Map<String, Object> m = svc.availability("http", 30, Set.of(1L, 3L), now).get(1L);

        assertThat(m).containsEntry("n", 8).containsEntry("fail", 4).containsEntry("bad_hours", 3);   // üst alanlar değişmedi
        Map<Integer, Map<String, Object>> w = windows(m);
        assertThat(w.keySet()).containsExactly(1, 7, 15, 30);
        assertThat(w.get(1)).containsEntry("n", 4).containsEntry("fail", 2).containsEntry("bad_hours", 1).containsEntry("up_pct", 50.0);
        assertThat(w.get(7)).containsEntry("n", 6).containsEntry("fail", 3).containsEntry("bad_hours", 2).containsEntry("up_pct", 50.0);
        assertThat(w.get(15)).containsEntry("n", 7).containsEntry("fail", 4).containsEntry("bad_hours", 3);
        assertThat(w.get(30)).containsEntry("n", 8).containsEntry("fail", 4).containsEntry("bad_hours", 3).containsEntry("up_pct", 50.0);
        // Saat dilimi başına DÖNEM İÇİ hata adedi, en yeni dilim önce (2026-09-24: "o saatte 5 hata varsa 5 hata yazsın").
        String hA = ISO.format(now.minus(2, ChronoUnit.HOURS)).substring(0, 13);
        String hB = ISO.format(now.minus(10, ChronoUnit.DAYS)).substring(0, 13);
        String hC = ISO.format(dayAgoHour).substring(0, 13);
        assertThat(w.get(1).get("slots")).isEqualTo(List.of(Map.of("h", hA, "fail", 2)));                 // kova C'nin hatası dönem dışı
        assertThat(w.get(7).get("slots")).isEqualTo(List.of(Map.of("h", hA, "fail", 2), Map.of("h", hC, "fail", 1)));
        assertThat(w.get(15).get("slots")).isEqualTo(List.of(Map.of("h", hA, "fail", 2), Map.of("h", hC, "fail", 1), Map.of("h", hB, "fail", 1)));
        // kontrolü olmayan monitör: her dönem n=0, up_pct null
        assertThat(windows(svc.availability("http", 30, Set.of(3L), now).get(3L)).values())
                .allSatisfy(x -> assertThat(x).containsEntry("n", 0).containsEntry("up_pct", null));
    }

    @Test
    @DisplayName("availability windows: dönem başına en yeni 6 hatalı saat dilimi döner (adetleriyle), bad_hours tam sayıyı korur")
    void availability_slotsCapped() {
        Instant now = Instant.now().truncatedTo(ChronoUnit.HOURS).plus(30, ChronoUnit.MINUTES);
        for (int h = 1; h <= 8; h++) {
            for (int i = 0; i < h; i++) checkAt(1, now.minus(h, ChronoUnit.HOURS).plus(i, ChronoUnit.MINUTES), null, "timeout");   // h. saatte h hata
        }
        Map<String, Object> day = windows(svc.availability("http", 30, Set.of(1L), now).get(1L)).get(1);
        assertThat(day).containsEntry("bad_hours", 8).containsEntry("fail", 36);
        @SuppressWarnings("unchecked") List<Map<String, Object>> slots = (List<Map<String, Object>>) day.get("slots");
        assertThat(slots).hasSize(6);
        assertThat(slots).extracting(s -> s.get("fail")).containsExactly(1, 2, 3, 4, 5, 6);   // en yeni önce; 5. dilim "5 hata"
        assertThat(slots).extracting(s -> (String) s.get("h")).isSortedAccordingTo(java.util.Comparator.reverseOrder());
    }

    @Test
    @DisplayName("availability windows: istenen pencereden uzun dönem atlanır; listede olmayan pencere sona eklenir")
    void availability_windowsFollowDays() {
        Instant now = Instant.now();
        checkAt(1, now.minus(1, ChronoUnit.HOURS), 100L, null);
        assertThat(windows(svc.availability("http", 7, Set.of(1L), now).get(1L)).keySet()).containsExactly(1, 7);
        assertThat(windows(svc.availability("http", 90, Set.of(1L), now).get(1L)).keySet()).containsExactly(1, 7, 15, 30, 90);
    }
}
