package com.sitemonitor.service;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.Map;
import java.util.Set;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Kart mini trendi (2026-09-12): NATİF SQL gerçek motorda (H2, Postgres kipi) koşar — kova/pencere
 * sözdizimi ve sütun adları (Hibernate snake_case) burada doğrulanır. Tarihler KAYAN (now'dan).
 */
class MonitorSparklineServiceTest {

    private static final DateTimeFormatter ISO =
            DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss").withZone(ZoneOffset.UTC);

    JdbcTemplate jdbc;
    MonitorSparklineService svc;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource ds = new DriverManagerDataSource(
                "jdbc:h2:mem:sparktest;DB_CLOSE_DELAY=-1;MODE=PostgreSQL", "sa", "");
        jdbc = new JdbcTemplate(ds);
        jdbc.update("DROP TABLE IF EXISTS http_checks");
        jdbc.update("DROP TABLE IF EXISTS http_monitors");
        jdbc.update("CREATE TABLE http_monitors(id BIGINT PRIMARY KEY, team_id BIGINT)");
        jdbc.update("CREATE TABLE http_checks(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, monitor_id BIGINT, "
                + "http_status INT, response_ms BIGINT, error VARCHAR(200), checked_at VARCHAR(19))");
        jdbc.update("INSERT INTO http_monitors VALUES (1, 5), (2, NULL), (3, 7)");
        svc = new MonitorSparklineService(jdbc);
    }

    private void check(long monitorId, int minutesAgo, Long ms, String error) {
        jdbc.update("INSERT INTO http_checks(monitor_id, http_status, response_ms, error, checked_at) VALUES (?,?,?,?,?)",
                monitorId, error == null ? 200 : null, ms, error, ISO.format(Instant.now().minus(minutesAgo, ChronoUnit.MINUTES)));
    }

    @Test
    @DisplayName("monitorTeams: id → takım (null takım korunur)")
    void monitorTeams() {
        Map<Long, Long> t = svc.monitorTeams("http");
        assertThat(t).containsEntry(1L, 5L).containsEntry(3L, 7L).containsKey(2L);
        assertThat(t.get(2L)).isNull();
    }

    @Test
    @DisplayName("sparklines: saatlik kovalar (adet/hata/ort. süre), son 5 kontrol kronolojik, up_pct; pencere dışı satır sayılmaz; görünmeyen id dönmez")
    void sparklines_bucketsLastAndUpPct() {
        // monitör 1: 7 kontrol son 2 saatte, biri hatalı; 1 kontrol 30 saat önce (pencere dışı)
        check(1, 5,   200L, null);
        check(1, 15,  300L, null);
        check(1, 25,  null, "timeout");
        check(1, 35,  250L, null);
        check(1, 45,  210L, null);
        check(1, 70,  400L, null);
        check(1, 100, 500L, null);
        check(1, 30 * 60, 999L, null);
        // monitör 3: hiç kontrol yok — yine de kayıt döner (n=0, up_pct null)
        Map<Long, Map<String, Object>> out = svc.sparklines("http", 24, Set.of(1L, 3L));

        assertThat(out).containsKeys(1L, 3L).doesNotContainKey(2L);
        Map<String, Object> m1 = out.get(1L);
        assertThat(m1).containsEntry("n", 7).containsEntry("fail", 1);
        assertThat((Double) m1.get("up_pct")).isEqualTo(85.7);
        @SuppressWarnings("unchecked") List<Map<String, Object>> buckets = (List<Map<String, Object>>) m1.get("buckets");
        assertThat(buckets).isNotEmpty();
        assertThat(buckets.stream().mapToInt(b -> (Integer) b.get("n")).sum()).isEqualTo(7);
        assertThat(buckets.stream().mapToInt(b -> (Integer) b.get("fail")).sum()).isEqualTo(1);
        assertThat(buckets).allSatisfy(b -> assertThat(((String) b.get("t")).length()).isEqualTo(13));   // yyyy-MM-ddTHH
        @SuppressWarnings("unchecked") List<Map<String, Object>> last = (List<Map<String, Object>>) m1.get("last");
        assertThat(last).hasSize(5);
        assertThat(last.get(4)).containsEntry("ok", true).containsEntry("ms", 200L);      // en yeni sonda
        assertThat(last.get(2)).containsEntry("ok", false);                              // 25 dk önceki hata
        assertThat(last).extracting(c -> (String) c.get("at")).isSorted();

        Map<String, Object> m3 = out.get(3L);
        assertThat(m3).containsEntry("n", 0);
        assertThat(m3.get("up_pct")).isNull();
    }

    @Test
    @DisplayName("hours üst sınırı 168; desteklenmeyen tür false; boş id kümesi boş harita")
    void guards() {
        assertThat(MonitorSparklineService.supports("http")).isTrue();
        assertThat(MonitorSparklineService.supports("domain")).isFalse();
        assertThat(MonitorSparklineService.supports(null)).isFalse();
        assertThat(svc.sparklines("http", 9999, Set.of())).isEmpty();
        assertThat(MonitorSparklineService.KINDS).containsKeys("http", "ping", "port", "dns", "keyword", "page", "pagespeed", "scripted");
    }
    @Test
    @DisplayName("availability: 30 gün toplam/hata/yüzde (iki ondalık) + hatalı saat kovası; pencere dışı satır sayılmaz; gün tavanı 90")
    void availability() {
        check(1, 5,   200L, null);
        check(1, 65,  null, "timeout");   // farklı saat kovası
        check(1, 66,  null, "timeout");   // aynı kova → bad_hours yine 1
        check(1, 3 * 24 * 60, 300L, null);
        check(1, 100 * 24 * 60, 300L, null);   // 100 gün önce — 90 gün tavanı dışında
        Map<Long, Map<String, Object>> out = svc.availability("http", 9999, Set.of(1L, 3L));
        Map<String, Object> m = out.get(1L);
        assertThat(m).containsEntry("n", 4).containsEntry("fail", 2).containsEntry("bad_hours", 1);
        assertThat((Double) m.get("up_pct")).isEqualTo(50.0);
        assertThat(out.get(3L)).containsEntry("n", 0).containsEntry("bad_hours", 0);
        assertThat(out.get(3L).get("up_pct")).isNull();
    }
}
