{{- if not .Values.secret.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "site-monitor.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "site-monitor.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  ADMIN_USERNAME: {{ .Values.secret.adminUsername | quote }}
  ADMIN_PASSWORD: {{ .Values.secret.adminPassword | quote }}
  DB_PASSWORD: {{ if .Values.postgresql.enabled -}}
    {{ required "postgresql.auth.password is required when postgresql.enabled=true" .Values.postgresql.auth.password | quote }}
  {{- else -}}
    {{ .Values.secret.dbPassword | quote }}
  {{- end }}
  SPRING_MAIL_USERNAME: {{ .Values.secret.smtpUser | quote }}
  SPRING_MAIL_PASSWORD: {{ .Values.secret.smtpPassword | quote }}
  SITE_MONITOR_EMAIL_FROM: {{ .Values.secret.emailFrom | quote }}
  SITE_MONITOR_SECRET_KEY: {{ .Values.secret.secretKey | quote }}
  HTTP_PROXY_USER: {{ .Values.secret.httpProxyUser | quote }}
  HTTP_PROXY_PASS: {{ .Values.secret.httpProxyPass | quote }}
{{- end }}
